"""Add summary column to contracts

Revision ID: 1cb60b2870f0
Revises: 660918047877
Create Date: 2025-06-16 15:38:25.070752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb60b2870f0'
down_revision = '660918047877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.drop_column('preview')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview', sa.TEXT(), nullable=True))
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
