"""Add category column to Contract

Revision ID: 660918047877
Revises: 600ddd2fbd80
Create Date: 2025-06-16 12:21:58.169382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660918047877'
down_revision = '600ddd2fbd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
